export { default as AddressIcon } from './AddressIcon'
export { default as ArrowRightIcon } from './ArrowRightIcon'
export { default as EmailIcon } from './EmailIcon'
export { default as FacebookIcon } from './FacebookIcon'
export { default as InstagramIcon } from './InstagramIcon'
export { default as PhoneIcon } from './PhoneIcon'
export { default as PinterestIcon } from './PinterestIcon'
export { default as TwitterIcon } from './TwitterIcon'