export { default as ArrowRight } from './ArrowRight'
export { default as Facebook } from './Facebook'
export { default as Instagram } from './Instagram'
export { default as Pinterest } from './Pinterest'
export { default as Twitter } from './Twitter'